version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: noraneko-postgres
    environment:
      POSTGRES_DB: noraneko_id
      POSTGRES_USER: noraneko
      POSTGRES_PASSWORD: dev_password
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noraneko -d noraneko_id"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # 将来的にサーバーもコンテナ化する場合
  # server:
  #   build: ./backend
  #   container_name: noraneko-server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgres://noraneko:dev_password@postgres:5432/noraneko_id?sslmode=disable

volumes:
  postgres_data: